DATASET_FOLDER = "/home/sureshp/Landslide/datasets/"
DATASET_TYPE = 'LANDSLIDE4SENSE' # LANDSLIDE4SENSE or KERELA or ITALY or SKIN_LESION
LEARNING_RATE = 0.00001
NUM_EPOCHS = 150
BATCH_SIZE = 32

print(f"DATASET_FOLDER: {DATASET_FOLDER}")
print(f"DATASET_TYPE: {DATASET_TYPE}")
print(f"LEARNING_RATE: {LEARNING_RATE}")
print(f"NUM_EPOCHS: {NUM_EPOCHS}")
print(f"BATCH_SIZE: {BATCH_SIZE}")

